import { GoogleGenAI } from '@google/genai';
import { TrapSignal, MarketData } from '../src/types.js';

let ai: GoogleGenAI | null = null;

export async function evaluateSignalWithAI(signal: TrapSignal, market: MarketData): Promise<{ approve: boolean; reasoning: string }> {
  // If simulation mode is active, bypass Gemini API calls to prevent performance bottleneck
  if (process.env.SIMULATION_MODE === 'true') {
    return {
      approve: true,
      reasoning: "SIMULATION_MODE active: automatically approved for backtesting."
    };
  }

  // If API key is missing, reject the trade safely
  if (!process.env.GEMINI_API_KEY) {
    console.warn('[AIFilter] GEMINI_API_KEY missing from environment. Rejecting signal.');
    return {
      approve: false,
      reasoning: "GEMINI_API_KEY is not configured in the server environment. Safety abort."
    };
  }

  // Lazy-load the AI client
  if (!ai) {
    ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
  }

  const prompt = `You are an expert algorithmic trading risk manager. Your job is to review an automated trading signal generated by a "Stacey Burke Sniper" logic system and decide if it is safe to execute.

Here are the details of the trade setup:
- Asset: ${market.displayName} (${market.symbol})
- Direction: ${signal.direction}
- Pattern Triggered: ${signal.pattern}
- Key Level Trapped: ${signal.levelType} at ${signal.keyLevel.toFixed(5)}
- Timing Gate: ${signal.timingGate}
- Trigger Price: ${signal.triggerPrice.toFixed(5)}
- Suggested Stop Loss: ${signal.suggestedStopLoss} pips/points
- Confluence Grade (1-5): ${signal.grade} Stars
- Details: ${signal.details}

Market Context:
- Signal Day Type: ${market.signalDay}
- Current HOD (High of Day): ${market.hod.toFixed(5)}
- Current LOD (Low of Day): ${market.lod.toFixed(5)}

Analyze this setup against the Stacey Burke Smart Money Master Playbook:
1. Is the timing gate appropriate? (Must be within active NY/London/Asian session limits. Reject "Gap Time").
2. Is the Stop Loss reasonable? (Maximum 25 pips limit; 30 for Gold).
3. Does the Pattern align with the Level Type? (A HOD/HOS trap must be a SELL; a LOD/LOS trap must be a BUY).
4. Is it respecting the 00/50 rule? (Execution must be near a major 00 or 50 institutional level).
5. Does it acknowledge the Weekly Template? (Mid-week trades should be stop hunting Monday's Opening Range or Tuesday's Initial Balance).

If the setup looks like a low-probability continuation trade or trades directly into the 20 EMA, reject it.
You must respond in strict JSON format. Do not use Markdown wrappers, just output raw JSON:
{
  "approve": boolean,
  "reasoning": "A short, 2-sentence explanation of your decision."
}`;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
      config: {
        temperature: 0.2, // Low temp for logical consistency
        responseMimeType: "application/json",
      }
    });

    const jsonStr = response.text || "{}";
    const result = JSON.parse(jsonStr);

    console.log(`[AIFilter] Evaluated ${signal.symbol} ${signal.direction}. Approve: ${result.approve}`);
    return {
      approve: Boolean(result.approve),
      reasoning: result.reasoning || "No reasoning provided."
    };
  } catch (err: any) {
    console.error('[AIFilter] AI evaluation failed:', err.message);
    // Fail-safe: Reject trade if AI fails
    return {
      approve: false,
      reasoning: `AI evaluation failed: ${err.message}`
    };
  }
}
